---
title: RWS Kernregistraties
logo: "/assets/rws.svg"
favicon_ico: "/assets/favicon.ico"
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
color_scheme: rws
plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 3